/**
 * Author:  Hugo
 * Created: 11-Oct-2016
 */
DROP DATABASE IF EXISTS JODDEMAIL;
CREATE DATABASE JODDEMAIL;

GRANT ALL ON JODDEMAIL.* TO;

USE JODDEMAIL;

DROP TABLE IF EXISTS EMAILACCOUNT;
CREATE TABLE EMAILACCOUNT (
    ID int(11) NOT NULL auto_increment,
    EMAIL VARCHAR(45) NOT NULL default '',
    PASSWORD VARCHAR(45) NOT NULL default ''
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS EMAILINFO;
CREATE TABLE EMAILCONTENT (
    ID int(11) NOT NULL auto_increment,
    FROMEMAIL varchar(40) NOT NULL,
    SUBJECT varchar(40),
    SENDDATE date,
    RECEIVEDATE date,
    FOLDER INT(2) NOT NULL
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS EMAILMESSAGE;
CREATE TABLE EMAILMESSAGE (
    ID int(11) NOT NULL auto_increment,
    CONTENT text,
    EMAILID int(11),
    PRIMARY KEY (ID)
)

DROP TABLE IF EXISTS ATTACHMENT;
CREATE TABLE ATTACHMENT (
    ID int(11) NOT NULL auto_increment,
    FILENAME varchar(40) NOT NULL,
    FILEDATA BLOB,
    EMAILID int(11)
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS FOLDER;
CREATE TABLE FOLDER (
    ID int(2) NOT NULL auto_increment,
    FOLDERNAME varchar(40) NOT NULL default ''
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ATTACHMENT;
CREATE TABLE ATTACHMENT (
    ID int(11) NOT NULL auto_increment,
    CONTENT blob 
)
